site_name: BRB MOBILIDADE


theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  # logo: "icon-640.png"
  # favicon: "favicon-640.png"
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #003e7e
      accent: #003e7e
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #003e7e
      accent: #003e7e
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Início: index.md
  - Planejamento: 
    - Ferramentas: planejamentoProj/ferramentas.md
    - Cronograma planejado: planejamentoProj/cronogramas.md
    - Cronograma executado: planejamentoProj/cronograma_executado.md
    - Heat- Map: planejamentoProj/heat.md
    - Sites Avaliados: planejamentoProj/lista_Site.md
    - Processo de Design: planejamentoProj/process_des.md
    - Site Escolhido: planejamentoProj/site.md
  - Análise de Requisitos:
    - Perfil do usuário: analiseRequisitos/perfil_do_usuario.md
    - Personas: analiseRequisitos/personas.md
    - Cenários: analiseRequisitos/cenario.md
    - Aspectos éticos: analiseRequisitos/aspectos_eticos.md
    - Análise de tarefas:
      - Sobre: analiseRequisitos/analise_tarefas/sobre_analise_tarefas.md
      - HTA: analiseRequisitos/analise_tarefas/hta.md
      - CTT: analiseRequisitos/analise_tarefas/ctt.md
      - Planejamento dos Resultados da Análise de Tarefas: analiseRequisitos/analise_tarefas/planResAn.md
    - Análise de Requisitos II:
      - Princípios e Diretrizes Gerais: analiseRequisitos/principios_gerais.md
      - Metas de usabilidade: analiseRequisitos/metas_usa.md
      - Características Gerais: analiseRequisitos/caracteristicas_gerais.md
      - Guia de Estilo: analiseRequisitos/guia_de_estilo.md
  - Design, Avaliação e Desenvolvimento:
    - Nivel 1:
      - Planejamento do relato dos resultados Storyboard: designAvaliacao/storyboard/planejamentoResultados.md
  - Encontros: reunioes.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

custom_css: 
  -custom/custom.css
