site_name: BRB MOBILIDADE


theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  # logo: "icon-640.png"
  # favicon: "favicon-640.png"
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #003e7e
      accent: #003e7e
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #003e7e
      accent: #003e7e
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Início: index.md
  - Planejamento: 
    - Ferramentas: ferramentas.md
    - Cronograma planejado: cronogramas.md
    - Cronograma executado: cronograma_executado.md
    - Heat- Map: heat.md
    - Sites Avaliados: lista_Site.md
    - Processo de Design: process_des.md
    - Site Escolhido: site.md
  - Análise de Requisitos:
    - Perfil do usuário: perfil_do_usuario.md
    - Personas: personas.md
  - Encontros: reunioes.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

custom_css: 
  -custom/custom.css
